version: 2
updates:
  - package-ecosystem: "pnpm"
    directories:
      - "/runbotics/common"
      - "/runbotics/runbotics-orchestrator-ui"
      - "/runbotics/runbotics-desktop"
      - "/runbotics/runbotics-scheduler"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "develop"
    assignees:
      - "star-in-the-jar" # stanislaw-jarocki
      - "marcin-depcik"
    labels:
      - "security"
# if private registry is needed: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#registries
# versioning strategy: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy