version: '3.8'

services:
  runbotics-portainer:
    container_name: runbotics-portainer
    image: portainer/portainer-ce:2.20.3-alpine
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 127.0.0.1:9000:9000

  runbotics-postgresql:
    container_name: runbotics-postgresql
    image: postgres:13.2
    volumes:
      - runbotics:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=runbotics
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432

  runbotics-redis:
    container_name: runbotics-redis
    image: redis:6
    ports:
      - 6379:6379

volumes:
  runbotics:
    external: true
  portainer_data:
    external: false

networks:
  default:
    name: runbotics
    attachable: true
