services: 
  runbotics-postgresql:
    container_name: runbotics-postgresql
    image: postgres:13.2
    volumes:
      - runbotics:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=runbotics
      - POSTGRES_PASSWORD=runbotics
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - default
      - db
    ports:
      - 0.0.0.0:5432:5432
 
  runbotics-orchestrator:
    container_name: runbotics-orchestrator
    image: runbotics/runbotics-orchestrator:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://runbotics-postgresql:5432/runbotics
      - SPRING_DATASOURCE_USERNAME=runbotics
      - SPRING_DATASOURCE_PASSWORD=runbotics
      - BOT_INSTALLATION_FILE=./installation/RunBotics_2.0.7.zip
      - RUNBOTICS_SECRET=ODQ4ZDBjNTgzYTE3ZjI3ZTE2YzFiNDI4MGY0OTFmMGQ1YjM0ZjEyNzI1ZTBhOTk3Nzg0ZTkxNTk4Y2JmZGQ0ZTA0YjEyM2E1OGI3YTA4ODhiNTkxYjI0MzkzNGU3YTUwOWEzMjZjZDk2YTJkYjIyMzQzMjhhYTEwMTYwYTc0MmI=
    ports:
      - 0.0.0.0:8080:8080
    networks:
      - default
      - db
    depends_on:
      - runbotics-postgresql
    extra_hosts:
      - 'host.docker.internal:host-gateway'
 
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "0.0.0.0:9898:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - default
      - db
    depends_on:
      - runbotics-postgresql
 
  runbotics-redis:
    container_name: runbotics-redis
    image: redis:6
    ports:
      - 0.0.0.0:6379:6379
    networks:
      - default
      - db
      
  firefox:
    container_name: firefox
    image: selenium/standalone-firefox:140.0-geckodriver-0.36-grid-4.34.0-20250707
    ports:
      - 0.0.0.0:7901:7900
      - 0.0.0.0:4444:4444
    networks:
      - default
      - db
    shm_size: 2gb
    environment:
      SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
      SE_NODE_MAX_SESSIONS: 1
      JAVA_OPTS=-XX:ActiveProcessorCount: 1
 
volumes:
  runbotics:
    external: true
  portainer_data:
    external: false
  pgadmin-data:
 
networks:
  db:
  default:
    name: runbotics-dev
    attachable: true