# Use this docker-compose if you want to locally start in swarm mode
# deploy configuration works only in swarm mode
# in swarm mode container_name is not supported
# to run this in swarm mode run from runbotics repo
# `docker stack deploy -c docker-compose.dev.yml <your swarm service name>`

services:
  runbotics-portainer:
    image: portainer/portainer-ce:2.20.3-alpine
    restart: always
    networks:
      - hostnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  runbotics-postgresql:
    restart: on-failure
    image: postgres:13.2
    networks:
      - hostnet
    volumes:
      - runbotics:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=runbotics
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 20s
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix

  runbotics-orchestrator:
    restart: on-failure
    image: runbotics/runbotics-orchestrator:latest
    networks:
      - hostnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/runbotics
      - SPRING_DATASOURCE_USERNAME=runbotics
      - SPRING_DATASOURCE_PASSWORD=runbotics
      - BOT_INSTALLATION_FILE=./installation/RunBotics_2.0.7.zip
      - RUNBOTICS_SECRET=ODQ4ZDBjNTgzYTE3ZjI3ZTE2YzFiNDI4MGY0OTFmMGQ1YjM0ZjEyNzI1ZTBhOTk3Nzg0ZTkxNTk4Y2JmZGQ0ZTA0YjEyM2E1OGI3YTA4ODhiNTkxYjI0MzkzNGU3YTUwOWEzMjZjZDk2YTJkYjIyMzQzMjhhYTEwMTYwYTc0MmI=
    depends_on:
      - runbotics-postgresql
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/management/health | grep UP || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 180s

  runbotics-scheduler:
    image: runbotics/runbotics-scheduler:latest
    restart: on-failure
    networks:
      - hostnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
    environment:
      - RUNBOTICS_SCHEDULER_REDIS_HOST=localhost
      - RUNBOTICS_SCHEDULER_REDIS_PORT=6379
      - RUNBOTICS_DB_HOST=localhost
      - RUNBOTICS_DB_PORT=5432
      - RUNBOTICS_DB_USER=runbotics
      - RUNBOTICS_DB_PASSWORD=runbotics
      - RUNBOTICS_DB_DATABASE=runbotics
      - BOT_LOGS_DIRECTORY=./bot_logs
      - RUNBOTICS_SECRET=ODQ4ZDBjNTgzYTE3ZjI3ZTE2YzFiNDI4MGY0OTFmMGQ1YjM0ZjEyNzI1ZTBhOTk3Nzg0ZTkxNTk4Y2JmZGQ0ZTA0YjEyM2E1OGI3YTA4ODhiNTkxYjI0MzkzNGU3YTUwOWEzMjZjZDk2YTJkYjIyMzQzMjhhYTEwMTYwYTc0MmI=
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - ENCRYPTION_KEY=O3OTmXJpIIyUb3ByT4t65xblgsxfDGQu
      - TZ=UTC
      - MS_DISCOVERY_KEYS_URI=https://login.microsoftonline.com/common/discovery/v2.0/keys
      - IS_SSO_ENABLED="false"
    depends_on:
      - runbotics-redis
      - runbotics-postgresql

  runbotics-redis:
    image: redis:6
    networks:
      - hostnet
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 5
      start_period: 20s

  runbotics-nginx:
    image: nginx:1.25.3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD-SHELL", "service nginx status || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s

  runbotics-desktop:
    image: runbotics/runbotics-desktop:latest
    restart: on-failure
    networks:
      - hostnet
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        monitor: 10s
    environment:
      - RUNBOTICS_ENTRYPOINT_URL=http://localhost:8080
      - RUNBOTICS_SCHEDULER_ENTRYPOINT_URL=http://localhost:4000
      - RUNBOTICS_INSTALLATION_ID=admin
      - RUNBOTICS_USERNAME=runbotics@localhost
      - RUNBOTICS_PASSWORD=runbotics
      - RUNBOTICS_HOT_RELOAD=true
      - RUNBOTICS_BOT_COLLECTION=30bdfb61-841b-519b-ce54-1d0e56877f73
      - RUNBOTICS_LOGGER_FILE_MODE=false
      - RUNBOTICS_EXTENSION_DIR=./extensions
      - RUNBOTICS_PLUGINS_DIR=./plugins
      - CHROME_ADDRESS=http://chrome:4444
    depends_on:
      - runbotics-scheduler
      - runbotics-orchestrator
      - chrome

  chrome:
    image: selenium/standalone-chrome:132.0.6834.159-chromedriver-132.0.6834.159-grid-4.28.1-20250202
    networks:
      - hostnet

    shm_size: 2gb
    environment:
      SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
      SE_NODE_MAX_SESSIONS: 1
      JAVA_OPTS=-XX:ActiveProcessorCount: 1
      # SE_VNC_VIEW_ONLY: 1

networks:
  hostnet:
    external: true
    name: host

volumes:
  runbotics:
    name: runbotics
    external: false
  portainer_data:
    external: false
