export enum SAPLanguages {
    English = 'English',
    Polish = 'Polish',
    German = 'German',

    /* TODO: extend the enum with all SAP-supported languages */
    // If language is not installed in target server,
    // user should be notified when connection is not established  
    /*
    Afrikaans = 'Afrikaans',
    Arabic = 'Arabic',
    Bulgarian = 'Bulgarian',
    Catalan = 'Catalan',
    Chinese = 'Chinese',
    Chinese_Traditional = 'Chinese Traditional',
    Croatian = 'Croatian',
    Czech = 'Czech',
    Danish = 'Danish',
    Dutch = 'Dutch',
    Finnish = 'Finnish',
    French = 'French',
    Greek = 'Greek',
    Hebrew = 'Hebrew',
    Hungarian = 'Hungarian',
    Icelandic = 'Icelandic',
    Indonesian = 'Indonesian',
    Italian = 'Italian',
    Japanese = 'Japanese',
    Korean = 'Korean',
    Latvian = 'Latvian',
    Lithuanian = 'Lithuanian',
    Malay = 'Malay',
    Norwegian = 'Norwegian',
    Portuguese = 'Portuguese',
    Romanian = 'Romanian',
    Slovene = 'Slovene',
    Slovakian = 'Slovakian',
    Spanish = 'Spanish',
    Swedish = 'Swedish',
    Thai = 'Thai',
    Turkish = 'Turkish',
    Ukrainian = 'Ukrainian',
    */
};
