import { MigrationInterface, QueryRunner } from "typeorm";

export class Credentials1719908057135 implements MigrationInterface {
    name = 'Credentials1719908057135'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "fk_user_id_notification_process"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "fk_process_id_notification_process"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "fk_type_notification_process"`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" DROP CONSTRAINT "fk_authority_name"`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" DROP CONSTRAINT "fk_user_authority_user_id"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "fk_user_id_notification_bot"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "fk_bot_id_notification_bot"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "fk_type_notification_bot"`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" DROP CONSTRAINT "fk_bot_collection_user_user_id"`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" DROP CONSTRAINT "fk_bot_collection_user_bot_collection_id"`);
        await queryRunner.query(`CREATE TABLE "scheduler"."process_context" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "process_id" bigint NOT NULL, CONSTRAINT "REL_2436e0d0185232f33d7de31be3" UNIQUE ("process_id"), CONSTRAINT "PK_e7389e8eda74da686d637d7dbe4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheduler"."process_context_secret" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "tenant_id" uuid NOT NULL, "process_context_id" uuid NOT NULL, "secret_id" uuid NOT NULL, "order" integer NOT NULL, CONSTRAINT "REL_73e3b1df07fd1015969f9b9b51" UNIQUE ("secret_id"), CONSTRAINT "PK_2dc32cd0f720effcfd02bbaa14c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credential_template_attribute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "required" boolean NOT NULL, "type" character varying NOT NULL, "credential_template_id" character varying NOT NULL, "templateId" uuid, CONSTRAINT "PK_fb9643ff7794611a6abe693c3be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "credential_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "tenant_id" uuid, "description" character varying, "credentialsId" uuid, CONSTRAINT "UQ_8363f48a7697a4ee6e41f584b87" UNIQUE ("name"), CONSTRAINT "PK_94262abd8352fd19e4c500fff82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheduler"."credential" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "tenant_id" uuid NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by_id" bigint NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" bigint NOT NULL, "template_id" uuid NOT NULL, CONSTRAINT "PK_3a5169bcd3d5463cefeec78be82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheduler"."attribute" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "tenant_id" uuid NOT NULL, "description" character varying, "masked" boolean NOT NULL, "type " character varying NOT NULL, "secret_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by_id" bigint NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" bigint NOT NULL, "credential_id" uuid NOT NULL, CONSTRAINT "REL_459bfa2dbfac0fc450f1866d0b" UNIQUE ("secret_id"), CONSTRAINT "PK_b13fb7c5c9e9dff62b60e0de729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheduler"."secret" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "data" text NOT NULL, "iv" text NOT NULL, CONSTRAINT "PK_6afa4961954e17ec2d6401afc3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scheduler"."credential_collection" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "tenant_id" uuid NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "created_by_id" bigint NOT NULL, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_by_id" bigint NOT NULL, CONSTRAINT "PK_8928d022104b6c32bc3923e12ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jhi_authority_feature_keys_feature_key" ("authority" character varying(50) NOT NULL, "feature_key" character varying(50) NOT NULL, CONSTRAINT "PK_fd67870c3dc9a8edef27120f840" PRIMARY KEY ("authority", "feature_key"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1a93afcebdf4ec98e96c8c6aa" ON "jhi_authority_feature_keys_feature_key" ("authority") `);
        await queryRunner.query(`CREATE INDEX "IDX_269490e1f3a032fbc02eb833a1" ON "jhi_authority_feature_keys_feature_key" ("feature_key") `);
        await queryRunner.query(`CREATE TABLE "scheduler"."credential_collection_user" ("collection_id" uuid NOT NULL, "user_id" bigint NOT NULL, CONSTRAINT "PK_c1f6392fde3136c1b39d953bef5" PRIMARY KEY ("collection_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d667ee9c8f087bbeaa5744fc0" ON "scheduler"."credential_collection_user" ("collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_14c0e239df3748b2a116b22ba9" ON "scheduler"."credential_collection_user" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "notification_process_pkey"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "notification_bot_pkey"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "PK_3c678904d9bfedf7069902ed199" PRIMARY KEY ("process_id", "user_id")`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "PK_758fa16a3a1cd435f4e95dee020" PRIMARY KEY ("bot_id", "user_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_7b592798f4addb0d321581b70b" ON "notification_process" ("process_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e1a2280a824e267cdb588c74bd" ON "notification_process" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f110dd27f6b2da20b3f90cff63" ON "jhi_user_authority" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e230cfc3537bf2ea327f2c97c8" ON "jhi_user_authority" ("authority_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b63cf21b9a8d158b61d4358ab" ON "notification_bot" ("bot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_63e8bb25d071a7bbd6b80b2503" ON "notification_bot" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_84c327d024fd89e6d221a067ea" ON "bot_collection_user" ("bot_collection_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e88c501605e0063783ee80b7b0" ON "bot_collection_user" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context" ADD CONSTRAINT "FK_339e67792b324b8738cffe0194b" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context" ADD CONSTRAINT "FK_2436e0d0185232f33d7de31be33" FOREIGN KEY ("process_id") REFERENCES "process"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context_secret" ADD CONSTRAINT "FK_2a3cc0b689ec02ad07b29ca2cc7" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context_secret" ADD CONSTRAINT "FK_4c84d7884afcc4821043408b2ea" FOREIGN KEY ("process_context_id") REFERENCES "scheduler"."process_context"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context_secret" ADD CONSTRAINT "FK_73e3b1df07fd1015969f9b9b513" FOREIGN KEY ("secret_id") REFERENCES "scheduler"."secret"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credential_template_attribute" ADD CONSTRAINT "FK_f7975371420de3a578feb56131d" FOREIGN KEY ("templateId") REFERENCES "credential_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credential_template" ADD CONSTRAINT "FK_8858c92bf3c290efecd719b766e" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credential_template" ADD CONSTRAINT "FK_703ae6af6f58688622ebe122aa3" FOREIGN KEY ("credentialsId") REFERENCES "scheduler"."credential"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" ADD CONSTRAINT "FK_67b2188c3549e8631110fc03bec" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" ADD CONSTRAINT "FK_5f3dcfecb65a28b3657345507a2" FOREIGN KEY ("created_by_id") REFERENCES "jhi_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" ADD CONSTRAINT "FK_c7f06ea7b501efdd1a442d7f7e6" FOREIGN KEY ("updated_by_id") REFERENCES "jhi_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" ADD CONSTRAINT "FK_94262abd8352fd19e4c500fff82" FOREIGN KEY ("template_id") REFERENCES "credential_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" ADD CONSTRAINT "FK_53e11054a6e395e8adf1e1c97f6" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" ADD CONSTRAINT "FK_459bfa2dbfac0fc450f1866d0b4" FOREIGN KEY ("secret_id") REFERENCES "scheduler"."secret"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" ADD CONSTRAINT "FK_227839f8565d4424b6b02862fca" FOREIGN KEY ("created_by_id") REFERENCES "jhi_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" ADD CONSTRAINT "FK_3b4e96a3d1483e357a58cba5cb4" FOREIGN KEY ("updated_by_id") REFERENCES "jhi_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" ADD CONSTRAINT "FK_5645ccd9d2c5c129ee9bb49ae8b" FOREIGN KEY ("credential_id") REFERENCES "scheduler"."credential"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."secret" ADD CONSTRAINT "FK_2d1e3217ea4e8b4121900f8bbb6" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection" ADD CONSTRAINT "FK_3bd890535d007ae922b8a8d57fb" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection" ADD CONSTRAINT "FK_904fa54de57a33b4bedeb54ff9e" FOREIGN KEY ("created_by_id") REFERENCES "jhi_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection" ADD CONSTRAINT "FK_bdd0d73c04229928006483fd445" FOREIGN KEY ("updated_by_id") REFERENCES "jhi_user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jhi_authority_feature_keys_feature_key" ADD CONSTRAINT "FK_b1a93afcebdf4ec98e96c8c6aac" FOREIGN KEY ("authority") REFERENCES "jhi_authority"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "jhi_authority_feature_keys_feature_key" ADD CONSTRAINT "FK_269490e1f3a032fbc02eb833a12" FOREIGN KEY ("feature_key") REFERENCES "feature_key"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "FK_7b592798f4addb0d321581b70ba" FOREIGN KEY ("process_id") REFERENCES "process"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "FK_e1a2280a824e267cdb588c74bd9" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection_user" ADD CONSTRAINT "FK_4d667ee9c8f087bbeaa5744fc00" FOREIGN KEY ("collection_id") REFERENCES "scheduler"."credential_collection"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection_user" ADD CONSTRAINT "FK_14c0e239df3748b2a116b22ba9b" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "FK_f110dd27f6b2da20b3f90cff632" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "FK_e230cfc3537bf2ea327f2c97c84" FOREIGN KEY ("authority_name") REFERENCES "jhi_authority"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "FK_7b63cf21b9a8d158b61d4358abe" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "FK_63e8bb25d071a7bbd6b80b2503a" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" ADD CONSTRAINT "FK_84c327d024fd89e6d221a067ea6" FOREIGN KEY ("bot_collection_id") REFERENCES "bot_collection"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" ADD CONSTRAINT "FK_e88c501605e0063783ee80b7b0e" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bot_collection_user" DROP CONSTRAINT "FK_e88c501605e0063783ee80b7b0e"`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" DROP CONSTRAINT "FK_84c327d024fd89e6d221a067ea6"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "FK_63e8bb25d071a7bbd6b80b2503a"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "FK_7b63cf21b9a8d158b61d4358abe"`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" DROP CONSTRAINT "FK_e230cfc3537bf2ea327f2c97c84"`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" DROP CONSTRAINT "FK_f110dd27f6b2da20b3f90cff632"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection_user" DROP CONSTRAINT "FK_14c0e239df3748b2a116b22ba9b"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection_user" DROP CONSTRAINT "FK_4d667ee9c8f087bbeaa5744fc00"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "FK_e1a2280a824e267cdb588c74bd9"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "FK_7b592798f4addb0d321581b70ba"`);
        await queryRunner.query(`ALTER TABLE "jhi_authority_feature_keys_feature_key" DROP CONSTRAINT "FK_269490e1f3a032fbc02eb833a12"`);
        await queryRunner.query(`ALTER TABLE "jhi_authority_feature_keys_feature_key" DROP CONSTRAINT "FK_b1a93afcebdf4ec98e96c8c6aac"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection" DROP CONSTRAINT "FK_bdd0d73c04229928006483fd445"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection" DROP CONSTRAINT "FK_904fa54de57a33b4bedeb54ff9e"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential_collection" DROP CONSTRAINT "FK_3bd890535d007ae922b8a8d57fb"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."secret" DROP CONSTRAINT "FK_2d1e3217ea4e8b4121900f8bbb6"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" DROP CONSTRAINT "FK_5645ccd9d2c5c129ee9bb49ae8b"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" DROP CONSTRAINT "FK_3b4e96a3d1483e357a58cba5cb4"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" DROP CONSTRAINT "FK_227839f8565d4424b6b02862fca"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" DROP CONSTRAINT "FK_459bfa2dbfac0fc450f1866d0b4"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."attribute" DROP CONSTRAINT "FK_53e11054a6e395e8adf1e1c97f6"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" DROP CONSTRAINT "FK_94262abd8352fd19e4c500fff82"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" DROP CONSTRAINT "FK_c7f06ea7b501efdd1a442d7f7e6"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" DROP CONSTRAINT "FK_5f3dcfecb65a28b3657345507a2"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."credential" DROP CONSTRAINT "FK_67b2188c3549e8631110fc03bec"`);
        await queryRunner.query(`ALTER TABLE "credential_template" DROP CONSTRAINT "FK_703ae6af6f58688622ebe122aa3"`);
        await queryRunner.query(`ALTER TABLE "credential_template" DROP CONSTRAINT "FK_8858c92bf3c290efecd719b766e"`);
        await queryRunner.query(`ALTER TABLE "credential_template_attribute" DROP CONSTRAINT "FK_f7975371420de3a578feb56131d"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context_secret" DROP CONSTRAINT "FK_73e3b1df07fd1015969f9b9b513"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context_secret" DROP CONSTRAINT "FK_4c84d7884afcc4821043408b2ea"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context_secret" DROP CONSTRAINT "FK_2a3cc0b689ec02ad07b29ca2cc7"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context" DROP CONSTRAINT "FK_2436e0d0185232f33d7de31be33"`);
        await queryRunner.query(`ALTER TABLE "scheduler"."process_context" DROP CONSTRAINT "FK_339e67792b324b8738cffe0194b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e88c501605e0063783ee80b7b0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_84c327d024fd89e6d221a067ea"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63e8bb25d071a7bbd6b80b2503"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b63cf21b9a8d158b61d4358ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e230cfc3537bf2ea327f2c97c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f110dd27f6b2da20b3f90cff63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1a2280a824e267cdb588c74bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b592798f4addb0d321581b70b"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" DROP CONSTRAINT "PK_758fa16a3a1cd435f4e95dee020"`);
        await queryRunner.query(`ALTER TABLE "notification_process" DROP CONSTRAINT "PK_3c678904d9bfedf7069902ed199"`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "notification_bot_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD "created_at" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD "id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "notification_process_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "scheduler"."IDX_14c0e239df3748b2a116b22ba9"`);
        await queryRunner.query(`DROP INDEX "scheduler"."IDX_4d667ee9c8f087bbeaa5744fc0"`);
        await queryRunner.query(`DROP TABLE "scheduler"."credential_collection_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_269490e1f3a032fbc02eb833a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1a93afcebdf4ec98e96c8c6aa"`);
        await queryRunner.query(`DROP TABLE "jhi_authority_feature_keys_feature_key"`);
        await queryRunner.query(`DROP TABLE "scheduler"."credential_collection"`);
        await queryRunner.query(`DROP TABLE "scheduler"."secret"`);
        await queryRunner.query(`DROP TABLE "scheduler"."attribute"`);
        await queryRunner.query(`DROP TABLE "scheduler"."credential"`);
        await queryRunner.query(`DROP TABLE "credential_template"`);
        await queryRunner.query(`DROP TABLE "credential_template_attribute"`);
        await queryRunner.query(`DROP TABLE "scheduler"."process_context_secret"`);
        await queryRunner.query(`DROP TABLE "scheduler"."process_context"`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" ADD CONSTRAINT "fk_bot_collection_user_bot_collection_id" FOREIGN KEY ("bot_collection_id") REFERENCES "bot_collection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bot_collection_user" ADD CONSTRAINT "fk_bot_collection_user_user_id" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "fk_type_notification_bot" FOREIGN KEY ("type") REFERENCES "notification_type"("type") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "fk_bot_id_notification_bot" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_bot" ADD CONSTRAINT "fk_user_id_notification_bot" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "fk_user_authority_user_id" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jhi_user_authority" ADD CONSTRAINT "fk_authority_name" FOREIGN KEY ("authority_name") REFERENCES "jhi_authority"("name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "fk_type_notification_process" FOREIGN KEY ("type") REFERENCES "notification_type"("type") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "fk_process_id_notification_process" FOREIGN KEY ("process_id") REFERENCES "process"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification_process" ADD CONSTRAINT "fk_user_id_notification_process" FOREIGN KEY ("user_id") REFERENCES "jhi_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
