name: dependabot-rush-update

on:
  pull_request:
    branches: ["develop", "master"]
  push:
    branches:
      - 'dependabot/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure that the job only runs if the event is both a push to the dependabot branch
      # and a pull request on develop/master. You can customize this condition.
      - name: Run only on matching events
        if: >
          (github.event_name == 'push' && startsWith(github.ref, 'refs/heads/dependabot/')) &&
          (github.event_name == 'pull_request' && contains(github.base_ref, 'develop') || contains(github.base_ref, 'master'))
        run: echo "This runs only when both a push and a pull request event occurs."

