name: dependabot-rush-update

on:
  push:
    branches:
      - 'dependabot/something-2'
      - 'dependabot/npm_and_yarn/runbotics/runbotics-scheduler/develop/winston-daily-rotate-file-5.0.0'
      - 'dependabot/test'
      - 'dependabot/*' # Matches other similar dependabot branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
