name: Windows Bot build

on:
  push:
    branches: ['develop', 'master', 'feature/RPA-1097'] # todo remove feature/RPA-1097
  workflow_dispatch:

env:
  NODE_VERSION: 18.x
  RUSH: node ../common/scripts/install-run-rush.js
  PNPM: node ../common/scripts/install-run-pnpm.js
  
jobs:
  changes-detection:
    runs-on: windows-latest

    outputs:
      bot: ${{ steps.filter.outputs.bot }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Assign paths to scenarios
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            bot:
              - 'runbotics/runbotics-desktop/package.json'
  build-bot:
    needs: changes-detection # todo uncomment lines below
    # if: |
      # (github.ref == 'refs/heads/develop'
      # || github.ref == 'refs/heads/master'
      # || startsWith(github.ref, 'refs/heads/release/')
      # || startsWith(github.ref, 'refs/heads/hotfix/'))
      # && needs.changes-detection.outputs.bot == 'true'
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./runbotics/runbotics-desktop

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run:  ${{ env.RUSH }} install -t .

      - name: Build
        run: ${{ env.RUSH }} rebuild -t .

      - name: Rush deploy
        run: |
          mkdir -p ../common/deploy/runbotics-desktop
          ${{ env.RUSH }} deploy \
            --scenario runbotics-desktop \
            --target-folder ../common/deploy/runbotics-desktop \
            --overwrite
      - name: Assign package version
        uses: nyaa8/package-version@v1
        with:
          path: './runbotics/runbotics-desktop/package.json'

      - name: Navigate to /runbotics/common/deploy/runbotics-desktop/
      - run: cd ../common/deploy/runbotics-desktop/

      - name: Install rb-sdk
        run: |
          cd runbotics-sdk && \
            pnpm install --ignore-scripts && \
            cd ..

      - name: Install rb-common
        run: |
          cd runbotics-common && \
            pnpm install --ignore-scripts && \
            cd ..

      - name: Install npmrc
        run: |
          cp .npmrc ./runbotics-desktop && \
            cd runbotics-desktop && \
            pnpm add runbotics-common@file:../runbotics-common \
                @runbotics/runbotics-sdk@file:../runbotics-sdk \
                --ignore-scripts && \
            pnpm install --ignore-scripts && cd ..

      - name: Build rb-desktop
        run: |
          cd runbotics-desktop && \
            pnpm electron-builder && cd ..
