name: New Workflow

on:
  push:
    branches:
      - feature/new-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Your Build Step
        # Add your build/test commands here
        run: |
          echo "Running build/test commands..."
